apiVersion: v1
entries:
  tns-csi-driver:
  - apiVersion: v1
    appVersion: v0.10.0
    created: "2025-10-14T11:50:28.463693548-04:00"
    description: CSI Driver for TrueNAS SCALE
    digest: 0c0376f63e8b8a961c1622a9149530f171cb30077d9856caa28df95b9dd2e449
    name: tns-csi-driver
    urls:
    - cr-interne.denis.prive/outils/charts/v0.10.0/tns-csi-driver-v0.10.0.tgz
    version: v0.10.0
  - apiVersion: v1
    appVersion: v0.9.0
    created: "2025-10-14T11:50:28.464176022-04:00"
    description: CSI Driver for TrueNAS SCALE
    digest: 2422cef2bae632dbdd8d80cff8247320978e5d98e9b90fee1451269b776542c4
    name: tns-csi-driver
    urls:
    - cr-interne.denis.prive/outils/charts/v0.9.0/tns-csi-driver-v0.9.0.tgz
    version: v0.9.0
  - apiVersion: v1
    appVersion: dev
    created: "2025-10-14T11:50:28.463207877-04:00"
    description: CSI Driver for TrueNAS SCALE
    digest: 2ff1114b53b0694249c2685448c8c38a96f32638e72a6c8491fa36295fb99b28
    name: tns-csi-driver
    urls:
    - cr-interne.denis.prive/outils/charts/dev/tns-csi-driver-v0.0.0-dev.tgz
    version: v0.0.0-dev
generated: "2025-10-14T11:50:28.462529633-04:00"
