apiVersion: v1
entries:
  tns-csi-driver:
  - apiVersion: v1
    appVersion: v0.10.0
    created: "2026-01-16T09:42:17.157883007-05:00"
    description: CSI Driver for TrueNAS SCALE
    digest: 67490de9e94286ba644e48aaaa34df8efe85a88e14e52ed02a204d4870dbc28f
    name: tns-csi-driver
    urls:
    - ghcr.io/titou10titou10/v0.10.0/tns-csi-driver-v0.10.0.tgz
    version: v0.10.0
  - apiVersion: v1
    appVersion: v0.9.0
    created: "2026-01-16T09:42:17.158437225-05:00"
    description: CSI Driver for TrueNAS SCALE
    digest: 2422cef2bae632dbdd8d80cff8247320978e5d98e9b90fee1451269b776542c4
    name: tns-csi-driver
    urls:
    - ghcr.io/titou10titou10/v0.9.0/tns-csi-driver-v0.9.0.tgz
    version: v0.9.0
  - apiVersion: v1
    appVersion: dev
    created: "2026-01-16T09:42:17.157283609-05:00"
    description: CSI Driver for TrueNAS SCALE
    digest: bf81170b08dd5f3427d2821154d76ecbc98f48a1fd4ec9c2c8826259ab3bf9c0
    name: tns-csi-driver
    urls:
    - ghcr.io/titou10titou10/dev/tns-csi-driver-v0.0.0-dev.tgz
    version: v0.0.0-dev
generated: "2026-01-16T09:42:17.156535784-05:00"
