apiVersion: v1
entries:
  tns-csi-driver:
  - apiVersion: v1
    appVersion: v0.10.0
    created: "2025-10-14T12:01:38.572128406-04:00"
    description: CSI Driver for TrueNAS SCALE
    digest: 0c0376f63e8b8a961c1622a9149530f171cb30077d9856caa28df95b9dd2e449
    name: tns-csi-driver
    urls:
    - cr-interne.denis.prive/outils/charts/v0.10.0/tns-csi-driver-v0.10.0.tgz
    version: v0.10.0
  - apiVersion: v1
    appVersion: v0.9.0
    created: "2025-10-14T12:01:38.574365634-04:00"
    description: CSI Driver for TrueNAS SCALE
    digest: 2422cef2bae632dbdd8d80cff8247320978e5d98e9b90fee1451269b776542c4
    name: tns-csi-driver
    urls:
    - cr-interne.denis.prive/outils/charts/v0.9.0/tns-csi-driver-v0.9.0.tgz
    version: v0.9.0
  - apiVersion: v1
    appVersion: dev
    created: "2025-10-14T12:01:38.571605406-04:00"
    description: CSI Driver for TrueNAS SCALE
    digest: b7ea0e17f4bd037e521cd94467a38e73a8de07f0195fa3f3b54212320dad0c77
    name: tns-csi-driver
    urls:
    - cr-interne.denis.prive/outils/charts/dev/tns-csi-driver-v0.0.0-dev.tgz
    version: v0.0.0-dev
generated: "2025-10-14T12:01:38.570845034-04:00"
